### ISSUE TITLE
name to lowercase and underscore

### ISSUE THREAD

**Issue by anishshobithps** [tiarasjec/assets#2]
I map, assets.tiarasjec.in's XML and get the details, having name with underscore would benfit instead of space, I can split by `_` and then join `" "` for names directly and apply `toTitleCase` on the frontend. Or else it would require me to have simple JSON files etc.. 

Also keep the names in lowercase

CC @rabilrbl @Vineeth-03-Shenoy

**Comment by rabilrbl** [comment]
I didn't understand the first part.

Regarding spaces and lowercase I agree.

Need to change

**Comment by anishshobithps** [comment]
> I didn't understand the first part.
> 
> Regarding spaces and lowercase I agree.
> 
> Need to change

Basically, we have this XML file
![image](https://github.com/tiarasjec/assets/assets/38991749/8761075a-dd8e-4ee9-bf18-6433280f663c)

Instead of looping over the complicated JSON file we created, we can loop over the contents in the XML file then just get to display technical events and etc.. via the assets only.

This would eliminate from having the entire JSON file.

**Comment by rabilrbl** [comment]
@anishshobithps The XML file will have everything. I am planning to integrate all assets from next build here.
The file (index xml page) will be simply large and not worth for fetching it. It will cost delay
